### ISSUE TITLE
Unify pins libraries

### ISSUE THREAD

**Issue by GShotwell** [sellorm/python-pins#2]
This library and the official Rstudio library which is maintained by @javierluraschi have inconsistent behaviour, and this one doesn't work very well with Rstudio Connect. Would it be possible to figure out a way to either unify the two libraries, or change the name of one of them so that the Rstudio one could be `pip installed`?

I raised a parallel issue on the Rstudio repository: https://github.com/pinsjs/pinsjs/issues/60

**Comment by sellorm** [comment]
There isn't currently an official python pins library from RStudio. The PyPI pins "name" will be passed on to RStudio when one is created.

**Comment by GShotwell** [comment]
Oh great, have you communicated that to Javier?

**Comment by sellorm** [comment]
Javier left RStudio some time ago. Hadley is aware though.

**Comment by GShotwell** [comment]
Thanks, is there anything I can do to advocate for this? We're an rstudio customer and lack of python support on Rstudio Connect is causing us some headaches.

**Comment by sellorm** [comment]
Would probably be worth letting your CS rep know about your frustrations and maybe raising an issue on the official pins repo if you haven't already. https://github.com/rstudio/pins/issues

**Comment by sellorm** [comment]
The [PyPI hosted pins](https://pypi.org/project/pins/) is now an official [RStudio project](https://github.com/rstudio/pins-python).

Early stages of development, but Connect support already seems to work well.
